export const examples = [
  { id: "array", group: "structures", file: "array-operations.js",
    usage: 'console.log(JSON.stringify(arrayOperations()));',
    output: '{"values":[10,2,3],"removed":4,"copiedRange":[2,3],"sorted":[2,3,10]}' },
  { id: "arrays-hashing", group: "structures", file: "arrays-hashing.js",
    usage: 'console.log(JSON.stringify([...frequencyMap(["a", "b", "a"])]));\nconsole.log(JSON.stringify(uniqueValues([3, 1, 3, 2])));',
    output: '[["a",2],["b",1]]\n[3,1,2]' },
  { id: "stack", group: "structures", file: "stack.js",
    usage: 'const stack = new Stack();\nstack.push("first");\nstack.push("second");\nconsole.log(JSON.stringify([stack.peek(), stack.pop(), stack.pop(), stack.isEmpty]));',
    output: '["second","second","first",true]' },
  { id: "queue", group: "structures", file: "queue.js",
    usage: 'const queue = new Queue();\nqueue.enqueue("first");\nqueue.enqueue("second");\nconsole.log(JSON.stringify([queue.dequeue(), queue.peek(), queue.size]));',
    output: '["first","second",1]' },
  { id: "linked-list", group: "structures", file: "linked-list.js",
    usage: 'const list = new SinglyLinkedList();\nlist.append(2);\nlist.prepend(1);\nlist.append(3);\nlist.removeFirst(2);\nconsole.log(JSON.stringify([list.toArray(), list.tail.value, list.find(9)]));',
    output: '[[1,3],3,null]' },
  { id: "bst", group: "structures", file: "binary-search-tree.js",
    usage: 'const tree = new BinarySearchTree();\nfor (const value of [4, 2, 6, 1, 3, 4]) tree.insert(value);\nconsole.log(JSON.stringify([tree.inOrder(), tree.has(3), tree.has(5)]));',
    output: '[[1,2,3,4,6],true,false]' },
  { id: "min-heap", group: "structures", file: "min-heap.js",
    usage: 'const heap = new MinHeap();\nfor (const value of [5, 1, 4, 1]) heap.push(value);\nconst sorted = [];\nwhile (heap.size > 0) sorted.push(heap.pop());\nconsole.log(JSON.stringify(sorted));',
    output: '[1,1,4,5]' },
  { id: "graph", group: "structures", file: "graph.js",
    usage: 'const graph = createGraph([["A", "B"], ["A", "C"], ["B", "C"]], { vertices: ["D"] });\nconsole.log(JSON.stringify([...graph].map(([vertex, neighbours]) => [vertex, [...neighbours]])));',
    output: '[["D",[]],["A",["B","C"]],["B",["A","C"]],["C",["A","B"]]]' },
  { id: "linear-search", group: "algorithms", file: "linear-search.js",
    usage: 'console.log(JSON.stringify([linearSearch([8, 3, 5], 3), linearSearch([], 3)]));',
    output: '[1,-1]' },
  { id: "binary-search", group: "algorithms", file: "binary-search.js",
    usage: 'console.log(JSON.stringify([binarySearch([1, 3, 5, 7], 5), binarySearch([1, 3, 5, 7], 6)]));',
    output: '[2,-1]' },
  { id: "merge-sort", group: "algorithms", file: "merge-sort.js",
    usage: 'const values = [10, 2, -1, 2];\nconsole.log(JSON.stringify([mergeSort(values), values]));',
    output: '[[-1,2,2,10],[10,2,-1,2]]' },
  { id: "two-sum", group: "algorithms", file: "two-sum.js",
    usage: 'console.log(JSON.stringify([twoSum([2, 7, 11, 15], 9), twoSum([3, 3], 6), twoSum([1], 2)]));',
    output: '[[0,1],[0,1],null]' },
  { id: "two-pointers", group: "algorithms", file: "two-pointers.js",
    usage: 'console.log(JSON.stringify(twoSumSorted([1, 2, 4, 6, 9], 10)));',
    output: '[0,4]' },
  { id: "sliding-window", group: "algorithms", file: "sliding-window.js",
    usage: 'console.log(JSON.stringify([maxWindowSum([2, 1, 5, 1, 3, 2], 3), maxWindowSum([-5, -2, -3], 2)]));',
    output: '[9,-5]' },
  { id: "prefix-sums", group: "algorithms", file: "prefix-sums.js",
    usage: 'const prefix = buildPrefixSums([2, -1, 4, 3]);\nconsole.log(JSON.stringify([prefix, rangeSum(prefix, 1, 3)]));',
    output: '[[0,2,1,5,8],6]' },
  { id: "merge-intervals", group: "algorithms", file: "merge-intervals.js",
    usage: 'console.log(JSON.stringify(mergeIntervals([[8, 10], [1, 3], [2, 6], [10, 12]])));',
    output: '[[1,6],[8,12]]' },
  { id: "traversal", group: "algorithms", file: "traversal.js",
    usage: 'const graph = new Map([\n  ["A", new Set(["B", "C"])],\n  ["B", new Set(["D"])],\n  ["C", new Set()],\n  ["D", new Set()],\n]);\nconsole.log(JSON.stringify([bfs(graph, "A"), dfs(graph, "A")]));',
    output: '[["A","B","C","D"],["A","B","D","C"]]' },
  { id: "shortest-path", group: "algorithms", file: "shortest-path.js",
    usage: 'const graph = new Map([\n  ["A", new Set(["B", "C"])],\n  ["B", new Set(["D"])],\n  ["C", new Set(["D"])],\n  ["D", new Set()],\n  ["E", new Set()],\n]);\nconsole.log(JSON.stringify([shortestPath(graph, "A", "D"), shortestPath(graph, "A", "E")]));',
    output: '[["A","B","D"],null]' },
  { id: "backtracking", group: "algorithms", file: "backtracking.js",
    usage: 'console.log(JSON.stringify(permutations([1, 2, 3])));',
    output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' },
  { id: "dynamic-programming", group: "algorithms", file: "dynamic-programming.js",
    usage: 'console.log(JSON.stringify([minCoins([1, 3, 4], 6), minCoins([2], 3), minCoins([], 0)]));',
    output: '[2,-1,0]' },
];
